import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from _preamble import init_julia


def run(jl):
    jl.seval("""
        #Covariance matrices
        cn_I = transpose(temp_only_sim.ds.Cn.diag.arr)
        cf_I = transpose(temp_only_sim.ds.Cf.op.diag.arr)
        cphi_I = transpose(temp_only_sim.ds.Cϕ.op.diag.arr)
        nphi_I = transpose(temp_only_sim.ds.Nϕ.diag.arr)
        m_I = transpose(temp_only_sim.ds.M.diag.arr)
        b_I = transpose(temp_only_sim.ds.B.diag.arr)
        d_I = transpose(temp_only_sim.ds.D.op.diag.arr)
        g_I = transpose(temp_only_sim.ds.G.op.diag.arr)
        npzwrite(FILE_PATH * "cn_I.npz", cn_I)
        npzwrite(FILE_PATH * "cf_I.npz", cf_I)
        npzwrite(FILE_PATH * "cphi_I.npz", cphi_I)
        npzwrite(FILE_PATH * "nphi_I.npz", nphi_I)
        npzwrite(FILE_PATH * "m_I.npz", m_I)
        npzwrite(FILE_PATH * "b_I.npz", b_I)
        npzwrite(FILE_PATH * "d_I.npz", d_I)
        npzwrite(FILE_PATH * "g_I.npz", g_I)
    """)

    jl.seval("""
        #Covariance matrices
        cn_ee_P = transpose(polar_only_sim.ds.Cn[:E].diag.arr)
        cn_bb_P = transpose(polar_only_sim.ds.Cn[:B].diag.arr)
        cf_ee_P = transpose(polar_only_sim.ds.Cf[:E].diag.arr)
        cf_bb_P = transpose(polar_only_sim.ds.Cf[:B].diag.arr)
        cphi_P = transpose(polar_only_sim.ds.Cϕ.op.diag.arr)
        nphi_P = transpose(polar_only_sim.ds.Nϕ.diag.arr)
        m_ee_P = transpose(polar_only_sim.ds.M[:E].diag.arr)
        m_bb_P = transpose(polar_only_sim.ds.M[:B].diag.arr)
        b_ee_P = transpose(polar_only_sim.ds.B[:E].diag.arr)
        b_bb_P = transpose(polar_only_sim.ds.B[:B].diag.arr)
        d_ee_P = transpose(polar_only_sim.ds.D[:E].diag.arr)
        d_bb_P = transpose(polar_only_sim.ds.D[:B].diag.arr)
        npzwrite(FILE_PATH * "cn_ee_P.npz", cn_ee_P)
        npzwrite(FILE_PATH * "cn_bb_P.npz", cn_bb_P)
        npzwrite(FILE_PATH * "cf_ee_P.npz", cf_ee_P)
        npzwrite(FILE_PATH * "cf_bb_P.npz", cf_bb_P)
        npzwrite(FILE_PATH * "cphi_P.npz", cphi_P)
        npzwrite(FILE_PATH * "nphi_P.npz", nphi_P)
        npzwrite(FILE_PATH * "m_ee_P.npz", m_ee_P)
        npzwrite(FILE_PATH * "m_bb_P.npz", m_bb_P)
        npzwrite(FILE_PATH * "b_ee_P.npz", b_ee_P)
        npzwrite(FILE_PATH * "b_bb_P.npz", b_bb_P)
        npzwrite(FILE_PATH * "d_ee_P.npz", d_ee_P)
        npzwrite(FILE_PATH * "d_bb_P.npz", d_bb_P)
    """)

    jl.seval("""
        #Covariance matrices
        cn_ee_IP = transpose(polar_and_temp_sim.ds.Cn.ΣTE[4].diag.arr)
        cn_bb_IP = transpose(polar_and_temp_sim.ds.Cn.ΣB.diag.arr)
        cn_te_IP = transpose(polar_and_temp_sim.ds.Cn.ΣTE[2].diag.arr)
        cn_tt_IP = transpose(polar_and_temp_sim.ds.Cn.ΣTE[1].diag.arr)
        cf_ee_IP = transpose(polar_and_temp_sim.ds.Cf.op.ΣTE[4].diag.arr)
        cf_bb_IP = transpose(polar_and_temp_sim.ds.Cf.op.ΣB.diag.arr)
        cf_te_IP = transpose(polar_and_temp_sim.ds.Cf.op.ΣTE[2].diag.arr)
        cf_tt_IP = transpose(polar_and_temp_sim.ds.Cf.op.ΣTE[1].diag.arr)
        cphi_IP = transpose(polar_and_temp_sim.ds.Cϕ.op.diag.arr)
        nphi_IP = transpose(polar_and_temp_sim.ds.Nϕ.diag.arr)
        b_ee_IP = transpose(polar_and_temp_sim.ds.B.ΣTE[4].diag.arr)
        b_bb_IP = transpose(polar_and_temp_sim.ds.B.ΣB.diag.arr)
        b_te_IP = transpose(polar_and_temp_sim.ds.B.ΣTE[2].diag.arr)
        b_tt_IP = transpose(polar_and_temp_sim.ds.B.ΣTE[1].diag.arr)
        m_ee_IP = transpose(polar_and_temp_sim.ds.M.ΣTE[4].diag.arr)
        m_bb_IP = transpose(polar_and_temp_sim.ds.M.ΣB.diag.arr)
        m_te_IP = transpose(polar_and_temp_sim.ds.M.ΣTE[2].diag.arr)
        m_tt_IP = transpose(polar_and_temp_sim.ds.M.ΣTE[1].diag.arr)
        d_ee_IP = transpose(polar_and_temp_sim.ds.D.op.ΣTE[4].diag.arr)
        d_bb_IP = transpose(polar_and_temp_sim.ds.D.op.ΣB.diag.arr)
        d_te_IP = transpose(polar_and_temp_sim.ds.D.op.ΣTE[2].diag.arr)
        d_tt_IP = transpose(polar_and_temp_sim.ds.D.op.ΣTE[1].diag.arr)
        npzwrite(FILE_PATH * "d_ee_IP.npz", d_ee_IP)
        npzwrite(FILE_PATH * "d_bb_IP.npz", d_bb_IP)
        npzwrite(FILE_PATH * "d_te_IP.npz", d_te_IP)
        npzwrite(FILE_PATH * "d_tt_IP.npz", d_tt_IP)
        npzwrite(FILE_PATH * "cn_ee_IP.npz", cn_ee_IP)
        npzwrite(FILE_PATH * "cn_bb_IP.npz", cn_bb_IP)
        npzwrite(FILE_PATH * "cn_te_IP.npz", cn_te_IP)
        npzwrite(FILE_PATH * "cn_tt_IP.npz", cn_tt_IP)
        npzwrite(FILE_PATH * "cf_ee_IP.npz", cf_ee_IP)
        npzwrite(FILE_PATH * "cf_bb_IP.npz", cf_bb_IP)
        npzwrite(FILE_PATH * "cf_te_IP.npz", cf_te_IP)
        npzwrite(FILE_PATH * "cf_tt_IP.npz", cf_tt_IP)
        npzwrite(FILE_PATH * "cphi_IP.npz", cphi_IP)
        npzwrite(FILE_PATH * "nphi_IP.npz", nphi_IP)
        npzwrite(FILE_PATH * "m_ee_IP.npz", m_ee_IP)
        npzwrite(FILE_PATH * "m_bb_IP.npz", m_bb_IP)
        npzwrite(FILE_PATH * "m_te_IP.npz", m_te_IP)
        npzwrite(FILE_PATH * "m_tt_IP.npz", m_tt_IP)
        npzwrite(FILE_PATH * "b_ee_IP.npz", b_ee_IP)
        npzwrite(FILE_PATH * "b_bb_IP.npz", b_bb_IP)
        npzwrite(FILE_PATH * "b_te_IP.npz", b_te_IP)
        npzwrite(FILE_PATH * "b_tt_IP.npz", b_tt_IP)
    """)

    print("Done generating covariance matrices data!")


if __name__ == "__main__":
    jl = init_julia()
    run(jl)
