import jax
import jax.numpy as jnp
jax.config.update("jax_enable_x64", True)
from cmb_lensing.constants import *
from cmb_lensing.fields import *
from cmb_lensing.gradients import *
from cmb_lensing.lense_flow import *
from cmb_lensing.matrix_operators import *
from cmb_lensing.statistics import *
from cmb_lensing.wiener_filter import *
from scipy.optimize import minimize

#Given a real or simulated data set, return the f and phi which maximize
#the loglikelihood that this data was indeed generated by f and phi
def map_joint(data_set, num_steps = 30):

    #unpack the necessary data from the data set object
    noise_covariance = data_set.noise_covariance
    mixing_d = data_set.mixing_d
    mixing_g = get_scalar_identity(mixing_d)
    field_covariance = data_set.field_covariance
    phi_covariance = data_set.phi_covariance
    quadratic_estimate = data_set.quadratic_estimate
    mask = data_set.mask
    beam = data_set.beam
    data = data_set.data

    #set starting guesses for f and phi to all zeros
    field_predict = 0*data
    phi_predict = zero_scalar_field_like(data)

    #compute the hessian which we will use to calculate the step in the phi direction 
    hessian = pinv(phi_gradient_hessian(phi_covariance, quadratic_estimate))

    #loop for num_steps iterations
    for _ in range(num_steps):

        #compute the wiener filter of the predicted field
        field_predict = wiener_filter(field_predict, phi_predict, data, field_covariance, noise_covariance, mask, beam)

        #must mix f and phi before taking the gradient
        mixed_field, mixed_phi = mix(field_predict, phi_predict, mixing_d, mixing_g)
        mixed_grad_phi = mixed_grad_phi_logpdf(mixed_field, mixed_phi, data, noise_covariance, 
                                                phi_covariance, field_covariance, 
                                                mask, beam, mixing_d, mixing_g)

        #create a new partial function whose only input is alpha for use in the brent optimizer (we want to
        #minimize the value of this function w.r.t. the single parameter alpha)
        min_logpdf = partial(logpdf_at_phi_new, grad_phi = mixed_grad_phi, mixed_field = mixed_field, 
                             phi_predict = mixed_phi, data = data, beam = beam, mask = mask, field_covariance = field_covariance,
                             phi_covariance = phi_covariance, noise_covariance = noise_covariance,
                             mixing_d = mixing_d, mixing_g = mixing_g, hessian = hessian)
        
        #call the optimizer to find which alpha minimizes the best
        optimizer = minimize(min_logpdf, 1, method = 'BFGS') 
        alpha = optimizer.x[0]
 
        #now update phi with the best alpha choice
        phi_predict = phi_predict + alpha * hessian * mixed_grad_phi

    #return the three predicted values and the history object
    return field_predict, phi_predict

#This is the operator we multiply the phi gradient by in order to determine the total phi step
@jax.jit
def phi_gradient_hessian(phi_covariance, quadratic_estimate):
    cphi_inv = pinv(phi_covariance)
    qe_inv = pinv(quadratic_estimate)
    #hessian = Cphi^-1 + qe^-1
    hessian = cphi_inv + qe_inv
    return hessian

@jax.jit
def logpdf_at_phi_new(alpha, grad_phi, mixed_field, phi_predict, data,
                          beam, mask, field_covariance, 
                          phi_covariance, noise_covariance,
                          mixing_d, mixing_g, hessian):
    
    #the test phi will be the current phi prediction minus one step
    #in the opposite direction of the gradient of logpdf w.r.t. phi
    test_phi = phi_predict + alpha[0] * hessian * grad_phi

    #unmix the field by the test phi before we compute the logpdf
    field, phi = unmix(mixed_field, test_phi, mixing_d, mixing_g)

    #compute the value of logpdf at this test phi value
    logpdf_value = logpdf(field, phi, data, noise_covariance, 
                          phi_covariance, field_covariance, mask, beam)
    
    #return negative one times the logpdf
    return -1*logpdf_value