import jax
import jax.numpy as jnp
jax.config.update("jax_enable_x64", True)
from cmb_lensing.constants import *
from cmb_lensing.fields import *
from cmb_lensing.mixing import *
from cmb_lensing.gradients import *
from cmb_lensing.lense_flow import *
from cmb_lensing.matrix_operators import *
from cmb_lensing.statistics import *
from cmb_lensing.wiener_filter import *
from cmb_lensing.lbfgs import lbfgs_direction
from scipy.optimize import minimize_scalar, minimize
#NOTE minimize_scalar with Brent is faster for polarization (EB and TEB)
#whereas minimize with BFGS is faster for T-only (and constant step is fastest of all
#but only guaranteed to converge for toy simulated temperature fields)

#Adaptive profile-f tolerance schedule for phi_optimizer="lbfgs". By the envelope theorem the
#phi gradient is accurate only at the exact Wiener f, but early (when phi is far) a loose solve
#is enough and cheaper, so we solve loosely first and tighten toward tol_final near convergence.
#Discrete geometric levels over the first ramp_steps steps keep wiener_filter recompilations (tol
#is a static jit arg) to ramp_steps+1. Returns sched(step, rel_step) -> tol; rel_step (fraction
#phi moved last step) is passed for optional progress-based schedules but the default ramp uses
#only the step index (guaranteed to tighten regardless of the trajectory).
def wiener_tol_schedule(tol_init = 1e-1, tol_final = 1e-3, ramp_steps = 4):
    ratio = (tol_final / tol_init) ** (1.0 / ramp_steps)
    levels = [tol_init * ratio ** i for i in range(ramp_steps + 1)]
    def sched(step, rel_step = None):
        return levels[min(step, ramp_steps)]
    return sched

#Given a real or simulated data set, return the f and phi which maximize
#the loglikelihood that this data was indeed generated by f and phi
#use_mixing = True  -> the mixed-parametrization optimization (needs inverse lensing)
#use_mixing = False -> a mix-free joint MAP in (f, phi) coordinates (forward + adjoint only);
#                      useful with lensing backends whose inverse is approximate (e.g. NUFFT)
#phi_optimizer = "linesearch" -> the scipy scalar line search on the phi step (default; the
#                      mixed / mix-free branches above)
#phi_optimizer = "lbfgs" -> delensalot-style line-search-free L-BFGS quasi-Newton step in the
#                      mix-free (f, phi) parametrization. Fixes the mix-free line search's tiny
#                      step (alpha ~ 5e-4): it takes a fixed lbfgs_step (=1) along +H_k grad_phi,
#                      where H_k is the L-BFGS inverse Hessian seeded by hessian = pinv(Cphi^-1 +
#                      QE^-1) and refined by up to lbfgs_memory curvature pairs. Ignores use_mixing.
#wiener_tol: tolerance of the per-step Wiener (profile-f) solve. May be a float (constant) or a
#callable schedule sched(step, rel_step) -> tol (see wiener_tol_schedule). For phi_optimizer=
#"lbfgs" a tight solve matters: by the envelope theorem grad_phi_logpdf equals the true profile-
#likelihood gradient only at the exact Wiener f, so a loose solve (1e-1) feeds L-BFGS a biased
#gradient that wobbles/crawls, while 1e-3 converges in ~5 steps (relnorm 0.013 vs 0.46 at 20
#steps); an adaptive schedule solves loosely early (cheap CG) and tightens late. Default 1e-1
#keeps the existing line-search paths unchanged.
def map_joint(data_set, num_steps = 30, constant_step = False, use_mixing = True,
              phi_optimizer = "linesearch", lbfgs_memory = 20, lbfgs_step = 1.0,
              wiener_tol = 1e-1):

    #unpack the necessary data from the data set object
    noise_covariance = data_set.noise_covariance
    mixing_d = data_set.mixing_d
    #MAP joint method is invariant to G matrix so set to identity for simplicity here
    mixing_g = get_scalar_identity(mixing_d)
    field_covariance = data_set.field_covariance
    phi_covariance = data_set.phi_covariance
    quadratic_estimate = data_set.quadratic_estimate
    mask = data_set.mask
    beam = data_set.beam
    data = data_set.data

    #set starting guesses for f and phi to all zeros
    field_predict = 0*data #NOTE this is in general a TEB vector
    phi_predict = zero_scalar_field_like(data) #Phi only ever represents one singular field

    #compute the hessian which we will use to calculate the step in the phi direction
    hessian = pinv(phi_gradient_hessian(phi_covariance, quadratic_estimate))
    #H0 for the L-BFGS recursion is the same fixed curvature preconditioner
    apply_H0 = lambda field: hessian * field
    alpha = jnp.array(1.0)

    #L-BFGS curvature history (phi_optimizer == "lbfgs"); plain python lists carried across the
    #eager outer loop. s_i = phi_{i+1} - phi_i, y_i = -(grad_{i+1} - grad_i)
    s_list, y_list = [], []
    prev_grad_phi = None
    prev_increment = None
    #previous phi (start of last step), for the adaptive-tol relative-step measure
    prev_phi = None

    for step_index in range(num_steps):

        #per-step profile-f tolerance: a float is constant; a callable is an adaptive schedule
        #sched(step_index, rel_step), rel_step = ||phi moved last step|| / ||phi|| (None at step 0)
        if callable(wiener_tol):
            if prev_phi is None:
                rel_step = None
            else:
                phi_norm = jnp.sqrt(dot(phi_predict, phi_predict))
                dphi = phi_predict - prev_phi
                rel_step = float(jnp.sqrt(dot(dphi, dphi)) / phi_norm) if phi_norm > 0 else None
            tol_step = float(wiener_tol(step_index, rel_step))
        else:
            tol_step = wiener_tol
        prev_phi = phi_predict

        #compute the wiener filter of the predicted field (profiles f at the current phi)
        field_predict = wiener_filter(field_predict, phi_predict, data, field_covariance, noise_covariance, mask, beam, tol = tol_step)

        if phi_optimizer == "lbfgs":
            #delensalot-style line-search-free L-BFGS step in the mix-free parametrization.
            #The wiener_filter above already re-solves (profiles) f at the current phi.
            grad_phi = grad_phi_logpdf(field_predict, phi_predict, data, noise_covariance,
                                       phi_covariance, field_covariance, mask, beam)
            #now that we have the new gradient, store the curvature pair for the step just taken
            if prev_increment is not None:
                #minimized objective is -logpdf, so y = g_k - g_{k-1} = -(grad_k - grad_{k-1})
                y_prev = -1 * (grad_phi - prev_grad_phi)
                #curvature guard: only keep the pair if <s, y> > 0 (keeps H_k positive definite)
                if dot(prev_increment, y_prev) > 0:
                    s_list.append(prev_increment)
                    y_list.append(y_prev)
                    if lbfgs_memory is not None and len(s_list) > lbfgs_memory:
                        s_list.pop(0)
                        y_list.pop(0)
            #ascent direction on logpdf; with empty history == hessian * grad_phi (unit Fisher step)
            direction = lbfgs_direction(grad_phi, s_list, y_list, apply_H0, dot)
            increment = lbfgs_step * direction
            phi_predict = phi_predict + increment
            #store the ACTUAL step (not the raw direction) so s_{k} = phi_{k+1} - phi_k is exact
            prev_grad_phi = grad_phi
            prev_increment = increment
            continue

        if use_mixing:
            #must mix f and phi before taking the gradient
            mixed_field, mixed_phi = mix(field_predict, phi_predict, mixing_d, mixing_g)
            grad_phi = mixed_grad_phi_logpdf(mixed_field, mixed_phi, data, noise_covariance,
                                             phi_covariance, field_covariance,
                                             mask, beam, mixing_d, mixing_g)
            #partial over alpha for the line search (unmixes the field at each test phi)
            min_logpdf = partial(logpdf_at_phi_new, grad_phi = grad_phi, mixed_field = mixed_field,
                                 phi_predict = mixed_phi, data = data, beam = beam, mask = mask, field_covariance = field_covariance,
                                 phi_covariance = phi_covariance, noise_covariance = noise_covariance,
                                 mixing_d = mixing_d, mixing_g = mixing_g, hessian = hessian)
        else:
            #mix-free: gradient in the unlensed (f, phi) parametrization; no inverse lensing
            grad_phi = grad_phi_logpdf(field_predict, phi_predict, data, noise_covariance,
                                       phi_covariance, field_covariance, mask, beam)
            min_logpdf = partial(logpdf_at_phi_nomix, grad_phi = grad_phi, field = field_predict,
                                 phi_predict = phi_predict, data = data, beam = beam, mask = mask,
                                 field_covariance = field_covariance, phi_covariance = phi_covariance,
                                 noise_covariance = noise_covariance, hessian = hessian)

        if not constant_step:
            #call the optimizer to find which alpha minimizes the best
            optimizer = minimize(min_logpdf, 1, method = "BFGS") #Set a starting guess of "alpha = 1"
            alpha = optimizer.x[0]

        #take a step in the opposite direction of the gradient
        phi_predict = phi_predict + alpha * hessian * grad_phi

    #after max iterations have been looped through return the final learned fields
    return field_predict, phi_predict

#This is the operator we multiply the phi gradient by in order to determine the total phi step
@jax.jit
def phi_gradient_hessian(phi_covariance, quadratic_estimate):
    cphi_inv = pinv(phi_covariance)
    qe_inv = pinv(quadratic_estimate)
    hessian = cphi_inv + qe_inv
    return hessian

@jax.jit
def logpdf_at_phi_new(alpha, grad_phi, mixed_field, phi_predict, data,
                          beam, mask, field_covariance, 
                          phi_covariance, noise_covariance,
                          mixing_d, mixing_g, hessian):
    
    #the test phi will be the current phi prediction minus one step
    #in the opposite direction of the gradient of logpdf w.r.t. phi
    test_phi = phi_predict + alpha * hessian * grad_phi

    #unmix the field by the test phi before we compute the logpdf
    field, phi = unmix(mixed_field, test_phi, mixing_d, mixing_g)

    #compute the value of logpdf at this test phi value
    logpdf_value = logpdf(field, phi, data, noise_covariance, 
                phi_covariance, field_covariance, mask, beam)
    
    #return negative one times the logpdf
    return -1*logpdf_value

@jax.jit
def logpdf_at_phi_nomix(alpha, grad_phi, field, phi_predict, data,
                        beam, mask, field_covariance,
                        phi_covariance, noise_covariance, hessian):
    #mix-free line search: step phi directly (no mix/unmix) and evaluate logpdf at (field, test_phi)
    test_phi = phi_predict + alpha * hessian * grad_phi
    logpdf_value = logpdf(field, test_phi, data, noise_covariance,
                          phi_covariance, field_covariance, mask, beam)
    return -1 * logpdf_value

#Jitted line search which is just a dumb sequential lax.map
#NOTE this is here if we want it but is not currently used in the actual MAP_joint code
@jax.jit                                                                                                                                                                                    
def line_search(alpha, mixed_phi, hessian, mixed_grad_phi, mixed_field,
                mixing_d, mixing_g, data, noise_covariance,                                                                                                                                 
                phi_covariance, field_covariance, mask, beam):                                                                                                                              
                                                                                                                                                                                            
    alphas = jnp.linspace(0, alpha, 10)                                                                                                                                                     
                                                                                                                                                                                            
    def evaluate(test_alpha):                                                                                                                                                                    
        test_phi = mixed_phi + test_alpha * hessian * mixed_grad_phi
        field, phi = unmix(mixed_field, test_phi, mixing_d, mixing_g)                                                                                                                       
        return -1 * logpdf(field, phi, data, noise_covariance,                                                                                                                              
                           phi_covariance, field_covariance, 
                           mask, beam)                                                                                                                    
                                                                                                                                                                                            
    values = jax.lax.map(evaluate, alphas)                                                                                                                                                     
    return alphas[jnp.argmin(values)]
